# Basic Logging Configuration
# Minimal configuration for simple environments

# Wandb Settings
wandb_entity: "your_entity"
wandb_project: "basic_rl"
wandb_name: "basic_experiment"
wandb_group: "baseline"
wandb_tags: ["basic", "rl"]

# General Settings
num_agents: 1
clip_eps: 0.2

# Tracking Flags
track_learning_metrics: true
track_action_metrics: true
track_episodes: true
track_rewards: true
track_episode_length: true
track_terminations: true

# Tracked Metrics - Only basic episode metrics
tracked_metrics:
  reward:
    default_value: 0.0
    metric_type: "scalar"
    aggregation: "mean"
    wandb_name: "Episode / Reward"
    enabled: true